### PR TITLE
Milestone 6: Add forms

### PR DESCRIPTION
**Pull request by medaminedev66**
- Create forms to perform the following functions:
  - Creates a Post on behalf of the current_user.
  - Create a comment on behalf of the current_user.
- Allow Users to add likes to Posts.
- Add links to all the posts and users

### CODE REVIEW

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @medaminedev66, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Everything is working fine.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [x] Please add one or two users using `seed` data and also give the command in README file `rails db:seed` to load seed data into the local to test all the post, comment, and like features.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
> ## Required Changes ♻️
> * [x]  Please add one or two users using `seed` data and also give the command in README file `rails db:seed` to load seed data into the local to test all the post, comment, and like features.
> 

Hi @Dipeshtwis. I tried as much as I can to follow the requirements. You aske me to add `seed` as a required change and I still have no idea about it. can you send me an article to read about it? or can you explain it to me?

**Comment by Dipeshtwis** [comment]
> > ## Required Changes recycle
> > 
> > * [x]   Please add one or two users using `seed` data and also give the command in README file `rails db:seed` to load seed data into the local to test all the post, comment, and like features.
> 
> Hi @Dipeshtwis. I tried as much as I can to follow the requirements. You aske me to add `seed` as a required change and I still have no idea about it. can you send me an article to read about it? or can you explain it to me?

Hi @medaminedev66,

You can follow [this article ](https://www.xyzpub.com/en/ruby-on-rails/3.2/seed_rb.html) and also I want to explain and give you a little hint here to introduce you to seed.

Seed data - We use this to populate the database locally. In your case, I'm not able to create a user anyhow from the UI. So the easiest way to populate a user is to use `db/seeds.rb` file.

Suppose I want to create a user then we can make like this in your case. (we will write this code into `db/seeds.rb` file)

```ruby
user = User.create(Name: 'Dips', Photo: 'user photo', Bio: 'I am Dipesh Kumar, I am passionate about programming. In my free time, I like to play games, watch movies  and enjoy the sun.')

```
and then running `rails db:seed` from the command line will populate this user into the database. By then I will able to select the user and can create post, comment, or like on post.

Hope this will clear your doubt.
Thanks!

**Comment by medaminedev66** [comment]
Thanks, @Dipeshtwis for the explanation. Now I have a clear idea about it. I will try to add 2 users to `seeds.rb` file.
Thanks again.

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @medaminedev66, 

Good job on implementing the suggested changes. Now, I'm able to create posts, like, and comment with the populated user. Well Done.

Your project is complete!  There is nothing else to say other than... it's time to merge it :detective: 

Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
