### PR TITLE
Milestone 4: processing data in models

### PR DESCRIPTION
**Pull request by medaminedev66**
- Create model classes for all entities as shown in the ERD diagram.
- Set up associations between models.
- Create a method `recent_posts` that returns the 3 most recent posts for a given user in `User` model
- Create a method `update_counter` that updates the posts counter for a user in `Post` model.
- Create a method `recent_comments` which returns the 5 most recent comments for a given post isn `Post` model.
- Create a `update_comments_counter` method that updates the comments counter for a post in `Comment` model.
- Create a `update_likes_counter` method that updates the likes counter for a post in `Like` model.
- Create a method called `current_user` in `pplicationController` that returns the first user from a database.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @medaminedev66,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- The migration is not complete due to the likes table having no foreign key for the option{: column=>: AuthorId_id}? please fix the table in your migration file.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hi @dasileker, thanks for reviewing my project
I think the likes table has a foreign key for the option{: column=>: AuthorId_id}

image

**Comment by dasileker** [comment]
> Hi @dasileker, thanks for reviewing my project
> I think the likes table has a foreign key for the option{: column=>: AuthorId_id}
> 
> image
> 

Yes, it has but it's not passing in the migration, because you have add likes_to_user without foreign key.

**Comment by medaminedev66** [comment]
> Yes, it has but it's not passing in the migration, because you have add likes_to_user without foreign key.

I couldn't get it. I mentioned the foreign key in the reference. Here is my record: 
image

**Comment by dasileker** [comment]
> > Yes, it has but it's not passing in the migration, because you have add likes_to_user without foreign key.
> 
> I couldn't get it. I mentioned the foreign key in the reference. Here is my record: 
> image
> 
> 

That's the issue there in the foreign key, the foreign key is true or false

**Comment by medaminedev66** [comment]
> > > Yes, it has but it's not passing in the migration, because you have add likes_to_user without foreign key.
> > 
> > 
> > I couldn't get it. I mentioned the foreign key in the reference. Here is my record:
> > image
> 
> That's the issue there in the foreign key

Can you please show me the error that you got when you tried to migrate the db? I didn't get the issue to work on it or fix it. everything is working well with me

**Comment by medaminedev66** [comment]
Anyway I will try to set up the migration again

**Comment by dasileker** [comment]
> > > > Yes, it has but it's not passing in the migration, because you have add likes_to_user without foreign key.
> > > 
> > > 
> > > I couldn't get it. I mentioned the foreign key in the reference. Here is my record:
> > > image
> > 
> > That's the issue there in the foreign key
> 
> Can you please show me the error that you got when you tried to migrate the db? I didn't get the issue to work on it or fix it. everything is working well with me

After you set up the migration please start the server to see if it will show error on the migration or not.

**Comment by medaminedev66** [comment]
> > > > > Yes, it has but it's not passing in the migration, because you have add likes_to_user without foreign key.
> > > > 
> > > > 
> > > > I couldn't get it. I mentioned the foreign key in the reference. Here is my record:
> > > > image
> > > 
> > > 
> > > That's the issue there in the foreign key
> > 
> > 
> > Can you please show me the error that you got when you tried to migrate the db? I didn't get the issue to work on it or fix it. everything is working well with me
> 
> After you set up the migration please start the server to see if it will show error on the migration or not.

I don't have any errors. the migration that I have done works well after running rails db:migrate

**Comment by medaminedev66** [comment]
@dasileker, It would be helpful if you share with me a screenshot to understand the core of the problem

**Comment by dasileker** [comment]
> @dasileker, It would be helpful if you share with me a screenshot to understand the core of the problem

this is the screenshot 

Web capture_7-12-2021_17118_localhost

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @medaminedev66,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
